### ISSUE TITLE
Пробел и enter нажимают «Play»

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/ptp2021-5-2d-game#38]
* Нажимаю «Play» мышкой.
* Переношу руку на клавиатуру. 2 секунды играю. Умираю.
* Переношу руку на мышку, нажимаю «Play».
* Переношу руку на клавиатуру. 2 секунды играю. Умираю.
* Переношу руку на мышку, нажимаю «Play».
* …

Сделайте клавиши enter и пробел на главном экране эквивалентными выбору пункта «Play». Пробел удобнее нажимать, если левая рука на WASD, enter — если правая рука на стрелках.

Или другие горячие клавиши придумайте, если планируете пробел и enter использовать в других целях.

Лучше вообще к меню добавить клавиатурный интерфейс. Текущий пункт меню как-то выделен (рамкой, размером). Стрелки вверх-вниз перемещают выделение, пробел и ввод выбирают пункт.

**Comment by alien-agent** [comment]
С балансом пока проблемы. Спасибо за совет

**Comment by Mazdaywik** [comment]
Клавиатура в главном меню пока не работает. Запускал на этой версии браузера:

![image](https://user-images.githubusercontent.com/1309859/127629825-0b05e90d-40d9-4f83-9f1c-f19742fd6dad.png)

Удалось пройти три уровня и набрать 2994 очка!

**Comment by Mazdaywik** [comment]
А, да, он же ещё не влитый был. Что-то я тупанул.

**Comment by Mazdaywik** [comment]
Теперь всё работает! 266? очков (последнюю цифру не запомнил).
