### ISSUE TITLE
Механика 'default_weapon' работает неправильно

### ISSUE THREAD

**Issue by stasstaf** [bmstu-iu9/ptp2021-5-2d-game#48]
Оружие игроку даётся не на весь уровень, а в начале уровня на время бустера, что не логично. Также надо убрать бустеры с бонусным оружием из уровней, в которых данное оружие даётся по умолчанию.

**Comment by alien-agent** [comment]
Можно добавить к методу changeWeapon параметр permanent=false.
Если оружие дается LevelManager'ом, то permanent=true и player.fireBoosterDuration получает значение Number.MAX_VALUE. По окончанию уровня нужно не забыть отобрать у игрока бонусное оружие))

**Comment by Mazdaywik** [comment]
Имена переменных в тексте лучше выделять обратными кавычками (на букве «ё» в русской раскладке).

    Можно добавить к методу `changeWeapon` параметр `permanent=false`.

Будет выглядеть так:

Можно добавить к методу `changeWeapon` параметр `permanent=false`.
