### ISSUE TITLE
Медленные заставки

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/ptp2021-5-2d-game#73]
* Полсекунды играю, меня убивают.
* Жду, когда надуется планета.
* Жду, когда покажется меню.
* Жду, когда планета сдуется и покажется кораблик.
* Опять полсекунды играю, меня убивают.

Выходит, я дольше созерцаю надувание и сдувание планеты, чем, собственно, играю.

**Comment by alien-agent** [comment]
> * Полсекунды играю, меня убивают.
> * Жду, когда надуется планета.
> * Жду, когда покажется меню.
> * Жду, когда планета сдуется и покажется кораблик.
> * Опять полсекунды играю, меня убивают.
> 
> Выходит, я дольше созерцаю надувание и сдувание планеты, чем, собственно, играю.

Анимации были ускорены в #77 примерно на 50%. 
Баланс улучшен в #75. Теперь умереть за несколько секунд будет очень тяжело. Приятной игры :)
